export const DATA_VIEW_MODE = {
  TABLE: "table",
  GRID: "grid",
};
export const GENDER = {
  ALL: "all",
  MALE: "male",
  FEMALE: "female",
};
export const NATIONALITY = {
  AU: "AU",
  BR: "BR",
  CA: "CA",
  CH: "CH",
  DE: "DE",
  DK: "DK",
  ES: "ES",
  FI: "FI",
  FR: "FR",
  GB: "GB",
  IE: "IE",
  IR: "IR",
  NO: "NO",
  NL: "NL",
  NZ: "NZ",
  TR: "TR",
  US: "US",
};

export const NATIONALITY_HUMAN_NAME = {
  [NATIONALITY.AU]: "Australian",
  [NATIONALITY.BR]: "Brazilian",
  [NATIONALITY.CA]: "Canadian",
  [NATIONALITY.CH]: "Chinese",
  [NATIONALITY.DE]: "German",
  [NATIONALITY.DK]: "Danish",
  [NATIONALITY.ES]: "Spanish",
  [NATIONALITY.FI]: "Finn",
  [NATIONALITY.FR]: "French",
  [NATIONALITY.GB]: "British",
  [NATIONALITY.IE]: "Irish",
  [NATIONALITY.IR]: "Iranian",
  [NATIONALITY.NO]: "Norwegian",
  [NATIONALITY.NL]: "Netherlander",
  [NATIONALITY.NZ]: "New Zealander",
  [NATIONALITY.TR]: "Turkish",
  [NATIONALITY.US]: "American",
};
export const NATIONALITY_HUMAN_COLOR = {
  [NATIONALITY.AU]: "#9F1B69",
  [NATIONALITY.BR]: "#E864B2",
  [NATIONALITY.CA]: "#4461EC",
  [NATIONALITY.CH]: "#51C453",
  [NATIONALITY.DE]: "#33C5C9",
  [NATIONALITY.DK]: "#F98C39",
  [NATIONALITY.ES]: "#FA7F56",
  [NATIONALITY.FI]: "#2B94FF",
  [NATIONALITY.FR]: "#9F1B69",
  [NATIONALITY.GB]: "#E864B2",
  [NATIONALITY.IE]: "#4461EC",
  [NATIONALITY.IR]: "#51C453",
  [NATIONALITY.NO]: "#33C5C9",
  [NATIONALITY.NL]: "#F98C39",
  [NATIONALITY.NZ]: "#FA7F56",
  [NATIONALITY.TR]: "#2B94FF",
  [NATIONALITY.US]: "#9F1B69",
};
